name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write   # ✅ 給 Actions 寫入權限，才能 push gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g prettier
      - run: prettier --check "**/*.{js,css,html}" || true
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # ✅ 使用這個 token
          publish_dir: ./
          publish_branch: gh-pages
